// 32BitComLibrary.idl : IDL source for 32BitComLibrary
//

// This file will be processed by the MIDL tool to
// produce the type library (My32BitComLibrary.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(2e547233-3ffc-400b-8222-640a81b84fd9),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IUserSecurity : IDispatch
{
	[id(1)] HRESULT SayHello([out, retval] BSTR* pHello);
};
[
	uuid(6e93d5da-e8fb-4a06-92aa-191bf716e618),
	version(1.0),
]
library My32BitComLibraryLib
{
	importlib("stdole2.tlb");
	[
		uuid(92863f96-28e8-415b-bd0e-bd75b781e149)
	]
	coclass UserSecurity
	{
		[default] interface IUserSecurity;
	};
};

import "shobjidl.idl";
